### ISSUE TITLE
link to howto is broken

### ISSUE THREAD

**Issue by daniel-wtd** [rsnapshot/rsnapshot#228] opened 2019-07-20 16:04 UTC
Hi y'all,

in the FAQ (https://rsnapshot.org/faq.html) the link to the HOWTO is broken.
It is currently pointing to https://rsnapshot.org/howto/1.2/rsnapshot-HOWTO.en.html#restoring_backups.

**Comment by sam-at-github** [comment] 2019-08-10 04:49
Duplicate of #92. Also see #106.

**Closed by sam-at-github** 2019-08-10 04:49 UTC

**Comment by daniel-wtd** [comment] 2019-08-11 09:59
I think you meant #93 , thanks a lot. will wait for #106

**Comment by sgpinkus** [comment] 2021-06-05 00:59
Thanks updated comment.
