### ISSUE TITLE
Additional per-backup excludes aren't properly merged

### ISSUE THREAD

**Issue by sgf-dma** [rsnapshot/rsnapshot#11] opened 2013-07-23 10:28 UTC
How to reproduce:
1. Specify additional per-backup exclude file (4th column in backup statement with '+' sign):
   
   ```
   backup  xxx@YYY:/etc/        ./t3    +exclude_file=/ZZZ/etc.exclude
   ```
   
   where
   
   ```
   # cat etc.exclude
   2.tmp
   ```
   
   And there is also global exclude file:
   
   ```
   # cat test.excl
   1.tmp
   ```
   
   specified earlier as
   
   ```
   exclude_file    /ZZZ/test.excl
   ```
2. Run configtest:
   
   ```
   # rsnapshot configtest
   Use of uninitialized value $parsed_opts{"exclude_file"} in concatenation (.) or string at /usr/local/bin/rsnapshot line 1809, <GEN0> line 228.
   require Lchown
   Lchown module loaded successfully
   Syntax OK
   ```
3. Run backup:
   
   ```
   # rsnapshot daily
   Use of uninitialized value $parsed_opts{"exclude_file"} in concatenation (.) or string at /usr/local/bin/rsnapshot line 1809, <GEN0> line 228.
   require Lchown
   Lchown module loaded successfully
   Setting locale to POSIX "C"
   echo 34130 > /var/run/rsnapshot.pid
   mkdir -m 0755 -p /ZZZ/daily.0/./
   /usr/local/bin/rsync -av --delete --numeric-ids --relative \
       --delete-excluded --exclude-from= --rsh=/usr/bin/ssh \
       xxx@YYY:/etc /ZZZ/daily.0/./t3
   receiving incremental file list
   created directory /ZZZ/daily.0/./t3
   etc/
   etc/1.tmp
   etc/2.tmp
   [..]
   ```

As you can see, '--exclude-from' option of rsync has no argument and both
files (excluded globally and per-backup) are included. When global exclude is
not used all will be similar ('--exclude-from' will not have argument).

Upd. rsnapshot 1.3.1

**Comment by bebehei** [comment] 2015-03-19 11:43
Do you use it with current master or the plain rsnapshot-1.3.1 release? Sadly there is no determination right now, to checkout if u use current master or rsnapshot-1.3.1, cause the version-variable is hardcoded to 1.3.1.

**Comment by sgf-dma** [comment] 2015-03-23 14:27
I've tried right now with current master. All the same:

    $ perl ./rsnapshot/rsnapshot -t -c ./rsnapshot.conf configtest
    Use of uninitialized value $parsed_opts{"exclude_file"} in concatenation (.) or string at ./rsnapshot/rsnapshot line 1769, <GEN0> line 215.
    Syntax OK
    $ perl ./rsnapshot/rsnapshot -v -t -c ./rsnapshot.conf  alpha
    Use of uninitialized value $parsed_opts{"exclude_file"} in concatenation (.) or string at ./rsnapshot/rsnapshot line 1769, <GEN0> line 215.
    echo 15543 > /var/run/rsnapshot.pid
    mkdir -m 0755 -p /home/dmitriym/Documents/rsnapshot/snap/alpha.0/
    /usr/bin/rsync -a --delete --numeric-ids --relative --delete-excluded \
        --exclude-from= /home/dmitriym/Documents/rsnapshot/test/ \
        /home/dmitriym/Documents/rsnapshot/snap/alpha.0/localhost/
    touch /home/dmitriym/Documents/rsnapshot/snap/alpha.0/

Config was:

    $ sed -ne '/^#\|^$/!p' rsnapshot.conf
    config_version  1.2
    snapshot_root   /home/dmitriym/Documents/rsnapshot/snap/
    cmd_cp          /bin/cp
    cmd_rm          /bin/rm
    cmd_rsync       /usr/bin/rsync
    cmd_ssh /usr/bin/ssh
    cmd_logger      /usr/bin/logger
    cmd_du          /usr/bin/du
    retain  alpha   6
    retain  beta    7
    retain  gamma   4
    verbose         3
    loglevel        3
    lockfile        /var/run/rsnapshot.pid
    exclude_file    /home/dmitriym/Documents/rsnapshot/global.excl
    backup  /home/dmitriym/Documents/rsnapshot/test/        localhost/      +exclude_file=/home/dmitriym/Documents/rsnapshot/test.excl

**Comment by bebehei** [comment] 2015-03-24 21:13
Thanks for the report. I've digged through it. It looks like the program-code is only half way completed in terms of per-backup-point-options. Cause rsnapshot right now mainly lacks of unit-tests, nobody noticed this.

**Comment by bebehei** [comment] 2015-03-27 15:50
I've figured out, what the problem is. I've submitted a quick-fix to my repository. Don't consider this as a real fix. It only contains workarounds. Find it at: bebehei/rsnapshot@g4d7ab90

To fix the source of the problem, we have to change the structure of `%config-vars`-hash.

    [bebe:~/code/build/rsnapshot/issue11] ± cat rsnapshot.issue11.conf 
    config_version1.2
    snapshot_root/home/bebe/code/build/rsnapshot/issue11/snap/
    cmd_cp/bin/cp
    cmd_rm/bin/rm
    cmd_rsync/home/bebe/code/build/rsnapshot/issue11/printenv
    #cmd_rsync/usr/bin/rsync
    cmd_ssh/usr/bin/ssh
    cmd_logger/usr/bin/logger
    cmd_du/usr/bin/du
    retainalpha6
    retainbeta7
    retaingamma4
    verbose3
    loglevel3
    lockfile/home/bebe/code/build/rsnapshot/issue11/rsnapshot.pid
    exclude_file/home/bebe/code/build/rsnapshot/issue11/files.exclude
    backup/srvlocalhost/
    backup/srvlocalhost/exclude_file=/home/bebe/code/build/rsnapshot/issue11/overwriting.exclude
    backup/srvlocalhost/+exclude_file=/home/bebe/code/build/rsnapshot/issue11/additional.exclude
    [bebe:~/code/build/rsnapshot/issue11] ± cat printenv 
    #!/bin/bash
    
    echo printenv: $*
    [bebe:~/code/build/rsnapshot/issue11] ± ./bin/rsnapshot --version
    rsnapshot 1.3.1-122-g4d7ab90

**Comment by kronthto** [comment] 2018-04-18 14:27
Is there any update on this issue? I've also encountered it using version `1.4.2-1` from the Debian Stretch repos.

``` sh
$ cat /etc/rsnapshot.conf
...
exclude	/tmp
exclude	/var/tmp
backup	root@remote:/	backupdir/	+exclude=/var/lib/mysql/
...

$ rsnapshot configtest
Use of uninitialized value $parsed_opts{"exclude"} in concatenation (.) or string at /usr/bin/rsnapshot line 1872, <GEN0> line 303.
Syntax OK

$ rsnapshot -t sync
...
/usr/bin/rsync -ax --delete --numeric-ids --relative --delete-excluded --exclude= ...
...
```

**Comment by ruedigerkupper** [comment] 2020-03-25 21:05
Confirming that this bug appears for "+exclude=...", too.

**Comment by dsrink** [comment] 2020-09-28 11:26
I am also seeing this issue on 1.4.3 running on RHEL8.

Actually there are several design problems in option parsing.

1) If  one specifies any include/exclude directive with "+" in the per-backup line, the key for %parsed_opts will be prefixed with "extra_" (line 1806 in my version). However, reading from that hash always occurs without the "extra_" prefix (see lines 1856, 1872, 1905, 1938). Therefore you see the empty value in this bug report.

2) The function parse_backup_opts overwrites $rsync_include_args and $rsync_include_file_args, due to re-declaring them with "my", close to the beginning of that function. 
This leads to global includes/excludes being thrown away if per-option includes are used, regardless of whether prefixed with "+" or not.
If I comment-out those two lines, it already runs much better.

3) per-option include/exclude/include_file/exclude_file statements are processed in an unfavourable ordering:
always first the globals, then the per-backup statements (at least if the two bugs mentioned above are worked around). After that, include/exclude are processed in the order of appearance. Include and Exclude are processed in the same variable sets.
\
This way, a per-backup line can never specify any "include" to override (or specify in more detail against) a global "exclude", because it will be passed to rsync in the order specified above.
rsnapshot should process include/include_file and exclude/exclude_file in separate lists, and also should have a possibility to prepend (instead of append) to those lists, if the user needs it.

Please let me suggest that the option parsing code needs some serious overhaul.

**Comment by sgpinkus** [comment] 2021-06-12 02:03
So, just reviewing this again:

> backup  xxx@YYY:/etc/        ./t3    +exclude_file=/ZZZ/etc.exclude

AFAIK "+ sign" is for appending arbitrary rsync options not for appending to rsnapshot config. I.e. only for `rsync_long_args` and `rsync_short_args`. `exclude_file` is an rsnapshot specific option.

There is only one example of "+" addition in man page. It says this:

```
               backup   /var/     localhost/   one_fs=1

                   This is the same as the other examples, but notice the fourth column.  This is how you specify per-backup-point options to over-ride global settings.  This
                   extra parameter can take several options, separated by commas.

                   It is most useful when specifying per-backup rsync excludes thus:

                   backup  root@somehost:/  somehost   +rsync_long_args=--exclude=/var/spool/

                   Note the + sign.  That tells rsnapshot to add to the list of arguments to pass to rsync instead of replacing the list.
```

I can confirm this works as intended on 1.4.3 and master for `rsync_long_args` and `rsync_short_args`. For `+exclude_file` seems to be silently ignored.

The man page should be updated to make a note about what limits of "+ sign".

Beyond that, to achieve appending an rsync exclude or exclude-from the correct syntax woulld be `... +rsync_long_args=--exclude=/var/spool/` and `... +rsync_long_args=--exclude-from=/some/file`

**Comment by sgpinkus** [comment] 2021-06-12 02:36
> Please let me suggest that the option parsing code needs some serious overhaul. The parse_backup_opts function (for per-backup options) has ~200 lines, the parse_config_file (for the global part) has ~1000 lines. This is hardly maintainable.

@dsrink well aware there are some code quality issues, that would be fixed in an ideal world. Remember this is Perl code circa 2004, that a lot of people have come to rely on. It's in maintenance mode, so major overhaul is not on the cards, as long as it's working for ~%99 of stable use cases.

**Closed by sgpinkus** 2021-06-12 02:36 UTC
Labels: bug
